### ISSUE TITLE
I don't see the ~/wtfd.conf file

### ISSUE THREAD

**Issue by dsl2022** [benbjohnson/wtf#63]
I have run the `make` and `install` as instructed, but I do not see the `wtfd.conf` file, only a `deploy.yml` file inside the github action folder that include the suggested credentials, 

```
          [http]
          domain    = "wtfdial.com"
          block-key = "${{ secrets.BLOCK_KEY }}"
          hash-key  = "${{ secrets.HASH_KEY }}"

          [google-analytics]
          measurement-id = "${{ secrets.GA_MEASUREMENT_ID }}"

          [github]
          client-id     = "${{ secrets.GH_CLIENT_ID }}"
          client-secret = "${{ secrets.GH_CLIENT_SECRET }}"
```

but I don't think that's where I should update the parameters. Would you please give me some hint?

**Comment by benbjohnson** [comment]
@JizongL You'll need to create a new `wtfd.conf` in your home directory. The [Development section](https://github.com/benbjohnson/wtf#development) gives a template of the file although you'll need to update the values that are marked as zeros.

```toml
[github]
client-id     = "00000000000000000000"
client-secret = "0000000000000000000000000000000000000000"

[http]
addr      = ":3000"
block-key = "0000000000000000000000000000000000000000000000000000000000000000"
hash-key  = "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
```
